# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: 
      context: "packages/api"
    ports: 
      - 3000:3000
    links:
      - mongo
    volumes:
      - ".:/opt/api"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081